# see package.yml for usage 
name: 'ROS Packaging'
description: 'Debian packaging on ROS Perception'
inputs:
  # if no inputs are given, the timestamp is used as the only version number
  version:  
    description: 'The version of the package to be generated. Other inputs ignored if provided.'
    required: false
    default: 'None'
  branch: 
    description: 'Optional: The branch name used in the minor version. Paths will be escaped.'
    required: false
    default: 'None'
  build-number: 
    description: 'Optional: Corresponds to the build number that invoked this. Patch version. '
    required: false
    default: 'None'
  pull-request-number: 
    description: 'Optional: Corresponds to the pull request that invoked this. Major version.'
    required: false
    default: 'None'
  dev-repo-entitlement: 
    description: 'Optional. If provided, will have access to the Cloudsmith dev repository for dependency download.'
    required: false
    default: 'None'
  release-repo-entitlement: 
    description: 'Optional. If provided, will have access to the Cloudsmith release repository for dependency download.'
    required: false
    default: 'None'
outputs:
  artifact-path:
    description: 'The file path where the artifact can be found'
  version:
    description: 'The version of the artifact.'

runs:
  using: 'docker'
  image: 'Dockerfile-amros'
  args: # see entrypoint.sh for the recipient of these - order matters
    - ${{ inputs.version }}
    - ${{ inputs.build-number }}
    - ${{ inputs.pull-request-number }}
    - ${{ inputs.branch }}
    - ${{ inputs.dev-repo-entitlement }}
    - ${{ inputs.release-repo-entitlement }}
