name: Validate Packaging
on: 
  push:
    branches-ignore:
      - master
env:
  PACKAGE_NAME: debian-package-test-action
jobs:
  default-version:
    runs-on: ubuntu-16.04
    name: Default version uses timestamps
    steps:
      - uses: actions/checkout@v1
      - name: Package
        id: package
        uses: ./  #use the current project relative to root
      - name: The generated package
        run: echo "The artifact is ${{ steps.package.outputs.artifact-path }}"
      - name: Validate package file provided exists
        uses: ./.github/actions/test@local
        with:
          package-file: ${{ steps.package.outputs.artifact-path }}      
  version:
    runs-on: ubuntu-16.04
    name: Package uses version provided
    env:
      VERSION: 0.0.13 #unlucky number to catch all edge cases
    steps:
      - uses: actions/checkout@v1
      - name: Package
        id: package
        uses: ./  #use the current project relative to root
        with:
          version: ${{ steps.version.env.version }}
      - name: The generated package
        run: echo "The artifact is ${{ steps.package.outputs.artifact-path }}"
      - name: Validate package file provided exists
        uses: ./.github/actions/test@local
        with:
          package-file: ${{ steps.package.outputs.artifact-path }}