name: Validate Packaging
on: 
  push:
    branches-ignore:
      - master
env:
  VERSION: 0.0.13 #unlucky number to catch all edge cases
  PACKAGE_NAME: debian-package-test-action
jobs:
  default-version:
    runs-on: ubuntu-16.04
    name: Default version uses timestamps
    steps:
      - uses: actions/checkout@v1
      - name: Package
        id: package
        uses: ./  #use the current project relative to root
      - name: The generated package
        run: echo "The artifact is ${{ steps.package.outputs.artifact-path }}"
      - name: Validate package file provided exists
        run: |
          ls -l /github
          ls -l /github/home
          ls -l /github/workspace
          ls -l ${{ steps.package.outputs.artifact-path }}
      - name: Validate package can be installed
        run: apt install -y ${{ steps.package.outputs.artifact-path }}
      - name: Validate installed package can be found
        run: ls -l /usr/local/bin/$PACKAGE_NAME
  version:
    runs-on: ubuntu-16.04
    name: Package uses version provided
    steps:
      - uses: actions/checkout@v1
      - name: Package
        id: package
        uses: ./  #use the current project relative to root
        with:
          version: $VERSION
      - name: The generated package
        run: echo "The artifact is ${{ steps.package.outputs.artifact-path }}"
      - name: Validate package file provided exists
        run: ls -l ${{ steps.package.outputs.artifact-path }}
      - name: Validate name is as we expected
        run: ls -l $PACKAGE_NAME_$VERSION_amd64.deb